In [1]:
import numpy as np

## MEAN ABSOLUTE ERROR

In [3]:
y_pred = np.array([1,1,0,0,1])
y_true = np.array([0.30,0.7,1,0,0.5])

In [4]:
def mae(y_pred,y_true):
    total_score = 0
    for yp,yt in zip(y_pred,y_true):
        total_score += abs(yp-yt)
    mae = total_score / len(y_true)
    print('total_err:',total_score)
    print(mae)

In [5]:
mae(y_pred,y_true)

total_err: 2.5
0.5


In [6]:
np.mean(np.abs(y_pred-y_true))

0.5

## LOG LOSS

IN LOG LOSS FORMULA - 1/N SUM((Y_TRUE * LOG(Y_PRED)) + (1 - Y_TRUE) * LOG(1 - Y_PRED))  
THE LOG(0) IS UNDEFINED SO WE NEED TO ADJUST IT

In [9]:
np.log(0)

C:\Users\AJU\AppData\Local\Temp\ipykernel_9244\2933082444.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(0)


-inf

In [10]:
np.log(0.0000001)

-16.11809565095832

In [11]:
np.log(1)

0.0

In [12]:
epsilon = 1e-15

In [13]:
y_pred

array([1, 1, 0, 0, 1])

MAKING 1 TO CLOSER VALUE TO 1 BUT NOT 1 AND 0 AS WELL

In [38]:
y_pred_now = [max(i, epsilon) for i in y_pred]
y_pred_now

[1, 1, 1e-15, 1e-15, 1]

In [42]:
y_pred_new = [min(i,1-epsilon) for i in y_pred_now]
y_pred_new

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [44]:
y_pred_new = np.array(y_pred_new)
np.log(y_pred_new)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [46]:
np.log(y_pred)

C:\Users\AJU\AppData\Local\Temp\ipykernel_9244\4184140517.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(y_pred)


array([  0.,   0., -inf, -inf,   0.])

In [48]:
y_true

array([0.3, 0.7, 1. , 0. , 0.5])

In [50]:
-np.mean(y_true*np.log(y_pred_new)+(1-y_true)*np.log(1-y_pred_new))

17.2696280766844

In [54]:
def log_loss(y_true,y_pred):
    epsilon = 1e-15
    y_pred_new = [max(i,epsilon) for i in y_pred]
    y_pred_new = [min(i,1-epsilon) for i in y_pred_new]
    y_pred_new = np.array(y_pred_new)
    return -np.mean(y_true*np.log(y_pred_new)+(1 - y_true)*np.log(1-y_pred_new))


In [56]:
log_loss(y_true,y_pred)

17.2696280766844

## MEAN SQUARED ERROR

In [75]:
np.mean(np.square(y_pred - y_true))

0.366

In [71]:
def mse(y_pred,y_true):
    total_err = 0
    for yt,yp in zip(y_pred,y_true):
        total_err += (yt - yp)**2
    mse = total_err/len(y_true)
    print(mse)

In [73]:
mse(y_pred,y_true)

0.366
